# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprofile',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appprofile',
            name='discription',
            field=models.TextField(blank=True),
        ),
    ]
