# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160109_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdownloadhistory',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppProfile'),
        ),
    ]
