# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160109_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdownloadhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
    ]
