# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160109_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprofile',
            name='rate_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
    ]
